apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: lukethep/jhipsterapp
      context: ../../jhipster-app
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
